"""create tables

Revision ID: 0002
Revises: 0001
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('customer_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers')),
    schema='ops'
    )
    op.create_table('settlements',
    sa.Column('settlement_id', sa.String(length=64), nullable=False),
    sa.Column('net_amount', sa.BigInteger(), nullable=False),
    sa.Column('utr', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('created', 'processed', 'failed', name='settlement_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('settlement_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('settlement_id', name=op.f('pk_settlements')),
    schema='ops'
    )
    op.create_index('ix_settlements_settlement_date', 'settlements', ['settlement_date'], unique=False, schema='ops')
    op.create_table('recon_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('tolerance_paise', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_recon_runs')),
    schema='recon'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('order_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'partially_refunded', 'refunded', 'cancelled', name='order_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("currency = 'INR'", name=op.f('ck_orders_currency_inr_only')),
    sa.CheckConstraint('order_amount >= 0', name=op.f('ck_orders_order_amount_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['ops.customers.customer_id'], name=op.f('fk_orders_customer_id')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders')),
    schema='ops'
    )
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False, schema='ops')
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('card', 'netbanking', 'upi', 'wallet', name='payment_method', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('created', 'authorized', 'captured', 'failed', 'refunded', 'partially_refunded', name='payment_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("currency = 'INR'", name=op.f('ck_payments_currency_inr_only')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['ops.customers.customer_id'], name=op.f('fk_payments_customer_id')),
    sa.ForeignKeyConstraint(['order_id'], ['ops.orders.order_id'], name=op.f('fk_payments_order_id')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments')),
    schema='ops'
    )
    op.create_index('ix_payments_captured_at', 'payments', ['captured_at'], unique=False, schema='ops')
    op.create_index('ix_payments_customer_id', 'payments', ['customer_id'], unique=False, schema='ops')
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False, schema='ops')
    op.create_table('case_truth',
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('is_exception', sa.Boolean(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('explained_amount', sa.BigInteger(), nullable=True),
    sa.Column('injection_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['ops.payments.payment_id'], name=op.f('fk_case_truth_payment_id')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_case_truth')),
    schema='gt'
    )
    op.create_table('adjustments',
    sa.Column('adjustment_id', sa.String(length=64), nullable=False),
    sa.Column('settlement_id', sa.String(length=64), nullable=True),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('chargeback', 'chargeback_reversal', 'dispute_hold', 'dispute_release', 'manual_credit', 'manual_debit', 'platform_fee', name='adjustment_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['ops.payments.payment_id'], name=op.f('fk_adjustments_payment_id')),
    sa.ForeignKeyConstraint(['settlement_id'], ['ops.settlements.settlement_id'], name=op.f('fk_adjustments_settlement_id')),
    sa.PrimaryKeyConstraint('adjustment_id', name=op.f('pk_adjustments')),
    schema='ops'
    )
    op.create_index('ix_adjustments_payment_id', 'adjustments', ['payment_id'], unique=False, schema='ops')
    op.create_index('ix_adjustments_settlement_id', 'adjustments', ['settlement_id'], unique=False, schema='ops')
    op.create_table('fees',
    sa.Column('fee_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('fee_amount', sa.BigInteger(), nullable=False),
    sa.Column('tax_amount', sa.BigInteger(), nullable=False),
    sa.Column('fee_rate_bps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('fee_amount >= 0', name=op.f('ck_fees_fee_non_negative')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_fees_tax_non_negative')),
    sa.ForeignKeyConstraint(['payment_id'], ['ops.payments.payment_id'], name=op.f('fk_fees_payment_id')),
    sa.PrimaryKeyConstraint('fee_id', name=op.f('pk_fees')),
    sa.UniqueConstraint('payment_id', name='uq_fees_payment_id'),
    schema='ops'
    )
    op.create_table('refunds',
    sa.Column('refund_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('created', 'processed', 'failed', name='refund_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_refunds_amount_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['ops.orders.order_id'], name=op.f('fk_refunds_order_id')),
    sa.ForeignKeyConstraint(['payment_id'], ['ops.payments.payment_id'], name=op.f('fk_refunds_payment_id')),
    sa.PrimaryKeyConstraint('refund_id', name=op.f('pk_refunds')),
    schema='ops'
    )
    op.create_index('ix_refunds_order_id', 'refunds', ['order_id'], unique=False, schema='ops')
    op.create_index('ix_refunds_payment_id', 'refunds', ['payment_id'], unique=False, schema='ops')
    op.create_table('exceptions',
    sa.Column('exception_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('exception_type', sa.Enum('MISSING_SETTLEMENT', 'DUPLICATE_PAYMENT', 'MISSING_REFUND', 'INCORRECT_REFUND_AMOUNT', 'FEE_MISMATCH', 'TAX_MISMATCH', 'PARTIAL_SETTLEMENT', 'SETTLEMENT_TIMING', 'UNEXPECTED_ADJUSTMENT', 'UNKNOWN_DISCREPANCY', name='exception_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('expected_net', sa.BigInteger(), nullable=False),
    sa.Column('actual_net', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('detected_by', sa.Enum('RULE', 'RESIDUAL', name='detected_by', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'REVIEW', 'ESCALATED', 'UNRESOLVED', name='exception_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('evidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('evidence_score IS NULL OR (evidence_score >= 0 AND evidence_score <= 100)', name=op.f('ck_exceptions_evidence_score_range')),
    sa.ForeignKeyConstraint(['payment_id'], ['ops.payments.payment_id'], name=op.f('fk_exceptions_payment_id')),
    sa.ForeignKeyConstraint(['run_id'], ['recon.recon_runs.run_id'], name=op.f('fk_exceptions_run_id')),
    sa.PrimaryKeyConstraint('exception_id', name=op.f('pk_exceptions')),
    schema='recon'
    )
    op.create_index('ix_exceptions_exception_type', 'exceptions', ['exception_type'], unique=False, schema='recon')
    op.create_index('ix_exceptions_status', 'exceptions', ['status'], unique=False, schema='recon')
    op.create_table('recon_results',
    sa.Column('result_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('expected_net', sa.BigInteger(), nullable=False),
    sa.Column('actual_net', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('MATCHED', 'PENDING_SETTLEMENT', 'EXCEPTION', name='recon_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['ops.payments.payment_id'], name=op.f('fk_recon_results_payment_id')),
    sa.ForeignKeyConstraint(['run_id'], ['recon.recon_runs.run_id'], name=op.f('fk_recon_results_run_id')),
    sa.PrimaryKeyConstraint('result_id', name=op.f('pk_recon_results')),
    sa.UniqueConstraint('run_id', 'payment_id', name='uq_recon_results_run_id'),
    schema='recon'
    )
    op.create_index('ix_recon_results_status', 'recon_results', ['status'], unique=False, schema='recon')
    op.create_table('settlement_items',
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('settlement_id', sa.String(length=64), nullable=False),
    sa.Column('item_type', sa.Enum('PAYMENT', 'REFUND', 'ADJUSTMENT', name='settlement_item_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('refund_id', sa.String(length=64), nullable=True),
    sa.Column('adjustment_id', sa.String(length=64), nullable=True),
    sa.Column('credit_amount', sa.BigInteger(), nullable=False),
    sa.Column('debit_fee', sa.BigInteger(), nullable=False),
    sa.Column('debit_tax', sa.BigInteger(), nullable=False),
    sa.Column('net_amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("item_type <> 'REFUND' OR net_amount <= 0", name=op.f('ck_settlement_items_refund_line_is_a_debit')),
    sa.CheckConstraint('(CASE WHEN payment_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN refund_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN adjustment_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name=op.f('ck_settlement_items_exactly_one_subject')),
    sa.CheckConstraint('credit_amount >= 0', name=op.f('ck_settlement_items_credit_non_negative')),
    sa.CheckConstraint('debit_fee >= 0', name=op.f('ck_settlement_items_debit_fee_non_negative')),
    sa.CheckConstraint('debit_tax >= 0', name=op.f('ck_settlement_items_debit_tax_non_negative')),
    sa.ForeignKeyConstraint(['adjustment_id'], ['ops.adjustments.adjustment_id'], name=op.f('fk_settlement_items_adjustment_id')),
    sa.ForeignKeyConstraint(['payment_id'], ['ops.payments.payment_id'], name=op.f('fk_settlement_items_payment_id')),
    sa.ForeignKeyConstraint(['refund_id'], ['ops.refunds.refund_id'], name=op.f('fk_settlement_items_refund_id')),
    sa.ForeignKeyConstraint(['settlement_id'], ['ops.settlements.settlement_id'], name=op.f('fk_settlement_items_settlement_id')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_settlement_items')),
    schema='ops'
    )
    op.create_index('ix_settlement_items_refund_id', 'settlement_items', ['refund_id'], unique=False, schema='ops')
    op.create_index('ix_settlement_items_settlement_id', 'settlement_items', ['settlement_id'], unique=False, schema='ops')
    op.create_index('uq_settlement_items_payment_once', 'settlement_items', ['payment_id'], unique=True, schema='ops', postgresql_where=sa.text("item_type = 'PAYMENT'"))
    op.create_table('investigations',
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('exception_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.Enum('BASELINE', 'AI', name='investigation_mode', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('reasoning_confidence', sa.Integer(), nullable=True),
    sa.Column('evidence_score', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('final_status', sa.Enum('OPEN', 'RESOLVED', 'REVIEW', 'ESCALATED', 'UNRESOLVED', name='final_exception_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('unexplained_amount', sa.BigInteger(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['recon.exceptions.exception_id'], name=op.f('fk_investigations_exception_id')),
    sa.PrimaryKeyConstraint('investigation_id', name=op.f('pk_investigations')),
    schema='recon'
    )
    op.create_index('ix_investigations_exception_id', 'investigations', ['exception_id'], unique=False, schema='recon')
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('SUPPORTS', 'CONTRADICTS', 'NEUTRAL', name='evidence_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('amount_contribution', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['recon.investigations.investigation_id'], name=op.f('fk_evidence_investigation_id')),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence')),
    schema='recon'
    )
    op.create_index('ix_evidence_investigation_id', 'evidence', ['investigation_id'], unique=False, schema='recon')
    op.create_table('investigation_steps',
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['recon.investigations.investigation_id'], name=op.f('fk_investigation_steps_investigation_id')),
    sa.PrimaryKeyConstraint('step_id', name=op.f('pk_investigation_steps')),
    sa.UniqueConstraint('investigation_id', 'seq', name='uq_investigation_steps_investigation_id'),
    schema='recon'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigation_steps', schema='recon')
    op.drop_index('ix_evidence_investigation_id', table_name='evidence', schema='recon')
    op.drop_table('evidence', schema='recon')
    op.drop_index('ix_investigations_exception_id', table_name='investigations', schema='recon')
    op.drop_table('investigations', schema='recon')
    op.drop_index('uq_settlement_items_payment_once', table_name='settlement_items', schema='ops', postgresql_where=sa.text("item_type = 'PAYMENT'"))
    op.drop_index('ix_settlement_items_settlement_id', table_name='settlement_items', schema='ops')
    op.drop_index('ix_settlement_items_refund_id', table_name='settlement_items', schema='ops')
    op.drop_table('settlement_items', schema='ops')
    op.drop_index('ix_recon_results_status', table_name='recon_results', schema='recon')
    op.drop_table('recon_results', schema='recon')
    op.drop_index('ix_exceptions_status', table_name='exceptions', schema='recon')
    op.drop_index('ix_exceptions_exception_type', table_name='exceptions', schema='recon')
    op.drop_table('exceptions', schema='recon')
    op.drop_index('ix_refunds_payment_id', table_name='refunds', schema='ops')
    op.drop_index('ix_refunds_order_id', table_name='refunds', schema='ops')
    op.drop_table('refunds', schema='ops')
    op.drop_table('fees', schema='ops')
    op.drop_index('ix_adjustments_settlement_id', table_name='adjustments', schema='ops')
    op.drop_index('ix_adjustments_payment_id', table_name='adjustments', schema='ops')
    op.drop_table('adjustments', schema='ops')
    op.drop_table('case_truth', schema='gt')
    op.drop_index('ix_payments_order_id', table_name='payments', schema='ops')
    op.drop_index('ix_payments_customer_id', table_name='payments', schema='ops')
    op.drop_index('ix_payments_captured_at', table_name='payments', schema='ops')
    op.drop_table('payments', schema='ops')
    op.drop_index('ix_orders_customer_id', table_name='orders', schema='ops')
    op.drop_table('orders', schema='ops')
    op.drop_table('recon_runs', schema='recon')
    op.drop_index('ix_settlements_settlement_date', table_name='settlements', schema='ops')
    op.drop_table('settlements', schema='ops')
    op.drop_table('customers', schema='ops')
    # ### end Alembic commands ###
